# Generated by Django 5.1 on 2024-11-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_stripecustomer_subscription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='stripe_invoice_id',
            field=models.CharField(max_length=255),
        ),
    ]
