# Generated by Django 5.1 on 2024-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='stripe_invoice_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
