# Generated by Django 5.1 on 2024-10-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_agency_name_alter_agency_address'),
        ('crm', '0019_alter_company_industry'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agency',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
    ]
