# Generated by Django 5.1 on 2024-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_category_ticket_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category_type',
            field=models.CharField(choices=[('client', 'Client'), ('agency', 'Agency')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
