# Generated by Django 5.1 on 2024-10-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('dev', 'Development'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
