# Generated by Django 5.1 on 2024-11-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_remove_agency_name'),
        ('tickets', '0019_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubject',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='ticketsubject',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ticketsubject',
            unique_together={('subject', 'agency')},
        ),
    ]
