# Generated by Django 5.1 on 2024-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
        ('crm', '0019_alter_company_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='company_contacts',
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(related_name='meetings_attended', to='crm.contact'),
        ),
    ]
