# Generated by Django 5.1 on 2024-09-17 07:03

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_activitylog_activity_type'),
        ('agencies', '0005_rename_name_agency_agency_name'),
        ('crm', '0019_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('No-show', 'No-show'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('location', models.CharField(choices=[('Online', 'Online'), ('In-person', 'In-person')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (75, '75 minutes'), (90, '90 minutes'), (105, '105 minutes'), (120, '120 minutes'), (135, '135 minutes'), (150, '150 minutes'), (165, '165 minutes'), (180, '180 minutes'), (195, '195 minutes'), (210, '210 minutes'), (225, '225 minutes'), (240, '240 minutes'), (255, '255 minutes'), (270, '270 minutes'), (285, '285 minutes'), (300, '300 minutes'), (315, '315 minutes'), (330, '330 minutes'), (345, '345 minutes'), (360, '360 minutes'), (375, '375 minutes'), (390, '390 minutes'), (405, '405 minutes'), (420, '420 minutes'), (435, '435 minutes'), (450, '450 minutes'), (465, '465 minutes'), (480, '480 minutes')])),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('to_do_task_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='agencies.agency')),
                ('associated_companies', models.ManyToManyField(related_name='meetings', to='crm.company')),
                ('attendees', models.ManyToManyField(related_name='meetings', to='crm.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
