# Generated by Django 5.1 on 2024-09-18 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_meeting_meetingattendee_delete_activitylog'),
        ('crm', '0019_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='associated_companies',
        ),
        migrations.AddField(
            model_name='meeting',
            name='agency_users',
            field=models.ManyToManyField(related_name='agency_meetings_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='company_contacts',
            field=models.ManyToManyField(related_name='meetings_attended', to='crm.contact'),
        ),
        migrations.DeleteModel(
            name='MeetingAttendee',
        ),
    ]
