# Generated by Django 5.1 on 2024-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_rename_contacts_meeting_company_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='to_do_task_message',
            field=models.TextField(blank=True, null=True, verbose_name='To Do Task Message'),
        ),
    ]
