# Generated by Django 5.1 on 2024-09-17 07:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_meeting_delete_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='content',
        ),
        migrations.AddField(
            model_name='meeting',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Details'),
        ),
    ]
