# Generated by Django 5.1 on 2024-09-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0004_meeting_to_do_task_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='details',
            field=models.TextField(blank=True, default='', verbose_name='Details'),
        ),
    ]
