# Generated by Django 5.1 on 2024-09-18 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0004_remove_meeting_agency_and_more'),
        ('crm', '0019_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='agency_users',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='company_contacts',
        ),
        migrations.AddField(
            model_name='meeting',
            name='associated_companies',
            field=models.ManyToManyField(related_name='meetings', to='crm.company'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
