# Generated by Django 5.1 on 2024-09-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0003_alter_agentsupportsupplier_agency_delete_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsupportsupplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agentsupportsupplier',
            name='users',
        ),
    ]
