# Generated by Django 5.1 on 2024-09-10 04:49

import agent_support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0005_alter_agentsupportsupplier_process_1_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=agent_support.models.upload_to_s3),
        ),
    ]
