# Generated by Django 5.1 on 2024-09-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_1_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/process_1/'),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_2_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/process_2/'),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_3_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/process_3/'),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_4_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/process_4/'),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='users',
            field=models.ManyToManyField(related_name='agent_support_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_support_suppliers', to='agent_support.agency'),
        ),
    ]
