# Generated by Django 5.1 on 2024-09-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_rename_name_agency_agency_name'),
        ('agent_support', '0002_agency_agentsupportsupplier_process_1_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_support_suppliers', to='agencies.agency'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
