# Generated by Django 5.1 on 2024-09-09 17:34

import agent_support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0004_remove_agentsupportsupplier_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='process_1_pdf',
            field=models.FileField(blank=True, null=True, upload_to=agent_support.models.upload_to_s3),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='process_2_pdf',
            field=models.FileField(blank=True, null=True, upload_to=agent_support.models.upload_to_s3),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='process_3_pdf',
            field=models.FileField(blank=True, null=True, upload_to=agent_support.models.upload_to_s3),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='process_4_pdf',
            field=models.FileField(blank=True, null=True, upload_to=agent_support.models.upload_to_s3),
        ),
    ]
