# Generated by Django 5.1 on 2024-09-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='business_focus',
            field=models.CharField(choices=[('corporate', 'Corporate Travel'), ('leisure', 'Leisure Travel'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agency',
            name='employees',
            field=models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('100+', '100+')], max_length=10),
        ),
    ]
