# Generated by Django 4.2.16 on 2024-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_create_site_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=255, verbose_name='Agency Name'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='business_focus',
            field=models.CharField(choices=[('corporate', 'Corporate Travel'), ('leisure', 'Leisure Travel'), ('mixed', 'Mixed')], max_length=20, verbose_name='Business Focus'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='company_reg_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Company Registration Number'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_name',
            field=models.CharField(max_length=100, verbose_name='Primary Contact Name'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='employees',
            field=models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('100+', '100+')], max_length=10, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='vat_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
