# Generated by Django 5.1 on 2024-09-06 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_rename_name_agency_agency_name'),
        ('crm', '0007_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='agencies.agency'),
            preserve_default=False,
        ),
    ]
