# Generated by Django 5.1 on 2024-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_company_create_date_alter_company_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linked_companies',
            field=models.ManyToManyField(blank=True, related_name='linked_to', to='crm.company'),
        ),
    ]
