# Generated by Django 5.1 on 2024-09-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_update_company_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Energy', 'Energy'), ('Transportation and Logistics', 'Transportation and Logistics'), ('Construction', 'Construction'), ('Education', 'Education'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Real Estate', 'Real Estate'), ('Media and Entertainment', 'Media and Entertainment'), ('Agriculture', 'Agriculture'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Telecommunications', 'Telecommunications'), ('Legal and Professional Services', 'Legal and Professional Services'), ('Fashion and Apparel', 'Fashion and Apparel'), ('Automotive', 'Automotive'), ('Mining and Metals', 'Mining and Metals'), ('Aerospace and Defence', 'Aerospace and Defence'), ('Environmental Services', 'Environmental Services')], max_length=255, null=True),
        ),
    ]
