# Generated by Django 5.1 on 2024-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_travel_booker_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_traveller_contact',
            field=models.BooleanField(default=False),
        ),
    ]
