# Generated by Django 5.1 on 2024-09-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_contact_is_travel_booker_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_vip_traveller_contact',
            field=models.BooleanField(default=False),
        ),
    ]
