# Generated by Django 5.1 on 2024-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('mining', 'Mining'), ('oil_gas_extraction', 'Oil and Gas Extraction'), ('pharmaceuticals', 'Pharmaceuticals'), ('biotechnology', 'Biotechnology'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('wholesale_trade', 'Wholesale Trade'), ('retail_trade', 'Retail Trade'), ('transportation', 'Transportation'), ('warehousing', 'Warehousing'), ('information', 'Information'), ('finance', 'Finance'), ('insurance', 'Insurance'), ('real_estate', 'Real Estate'), ('rental_leasing', 'Rental and Leasing'), ('professional_services', 'Professional Services'), ('scientific_services', 'Scientific Services'), ('technical_services', 'Technical Services'), ('management_companies', 'Management of Companies'), ('administrative_support', 'Administrative Support'), ('waste_management', 'Waste Management'), ('educational_services', 'Educational Services'), ('health_care', 'Health Care'), ('social_assistance', 'Social Assistance'), ('arts', 'Arts'), ('entertainment', 'Entertainment'), ('recreation', 'Recreation'), ('accommodation', 'Accommodation'), ('food_services', 'Food Services'), ('other_services', 'Other Services'), ('public_administration', 'Public Administration'), ('telecommunications', 'Telecommunications'), ('hospitality', 'Hospitality'), ('legal_services', 'Legal Services'), ('media_broadcasting', 'Media and Broadcasting'), ('energy', 'Energy'), ('renewable_energy', 'Renewable Energy'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace'), ('defence', 'Defence'), ('tourism', 'Tourism')], max_length=255),
        ),
    ]
