# Generated by Django 5.1 on 2024-09-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_rename_name_agency_agency_name'),
        ('crm', '0002_remove_company_agency_remove_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='agencies.agency'),
        ),
    ]
