# Generated by Django 5.1 on 2024-09-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='company_address',
        ),
    ]
