# Generated by Django 5.1 on 2024-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('New Client', 'New Client'), ('Trading', 'Trading'), ('No longer Trading', 'No longer Trading'), ('On hold', 'On hold'), ('Other', 'Other')], default='Lead', max_length=255),
        ),
    ]
