# Generated by Django 5.1 on 2024-09-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
