# Generated by Django 5.1 on 2024-09-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_contact_is_vip_traveller_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('fop_limit', models.CharField(blank=True, max_length=100)),
                ('invoice_references', models.TextField(blank=True)),
                ('corporate_hotel_rates', models.TextField(blank=True)),
                ('corporate_airline_fares', models.TextField(blank=True)),
                ('company_memberships', models.TextField(blank=True)),
                ('travel_policy', models.TextField(blank=True)),
                ('flight_notes', models.TextField(blank=True)),
                ('accommodation_notes', models.TextField(blank=True)),
                ('car_hire_notes', models.TextField(blank=True)),
                ('transfer_notes', models.TextField(blank=True)),
                ('rail_notes', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('online_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offline_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_fees', to='crm.company')),
            ],
        ),
    ]
