# Generated by Django 5.1 on 2024-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_companynotes_transactionfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('agriculture_forestry_fishing_hunting', 'Agriculture, Forestry, Fishing and Hunting'), ('mining_quarrying_oil_gas', 'Mining, Quarrying, and Oil and Gas Extraction'), ('pharmaceuticals_biotechnology', 'Pharmaceuticals and Biotechnology'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('wholesale_trade', 'Wholesale Trade'), ('retail_trade', 'Retail Trade'), ('transportation_warehousing', 'Transportation and Warehousing'), ('information', 'Information'), ('finance_insurance', 'Finance and Insurance'), ('real_estate_rental_leasing', 'Real Estate and Rental and Leasing'), ('professional_scientific_technical_services', 'Professional, Scientific, and Technical Services'), ('management_companies_enterprises', 'Management of Companies and Enterprises'), ('administrative_support_waste_management', 'Administrative and Support and Waste Management and Remediation Services'), ('educational_services', 'Educational Services'), ('health_care_social_assistance', 'Health Care and Social Assistance'), ('arts_entertainment_recreation', 'Arts, Entertainment, and Recreation'), ('accommodation_food_services', 'Accommodation and Food Services'), ('other_services', 'Other Services (except Public Administration)'), ('public_administration', 'Public Administration')], max_length=255),
        ),
    ]
