# Generated by Django 4.2.16 on 2024-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_company_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
