# Generated by Django 5.1 on 2024-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('manager', 'Manager'), ('sales', 'Sales')], default='admin', max_length=10),
        ),
    ]
