# Generated by Django 5.1 on 2024-09-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_remove_meeting_company_contacts_meeting_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='contacts',
            new_name='company_contacts',
        ),
    ]
