# Generated by Django 5.1 on 2024-09-24 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0005_alter_meeting_details'),
        ('crm', '0019_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('Connected', 'Connected'), ('Voicemail', 'Left Voicemail'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Disconnected', 'Disconnected')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(choices=[(1, '1 minutes'), (2, '2 minutes'), (3, '3 minutes'), (4, '4 minutes'), (5, '5 minutes'), (6, '6 minutes'), (7, '7 minutes'), (8, '8 minutes'), (9, '9 minutes'), (10, '10 minutes'), (11, '11 minutes'), (12, '12 minutes'), (13, '13 minutes'), (14, '14 minutes'), (15, '15 minutes'), (16, '16 minutes'), (17, '17 minutes'), (18, '18 minutes'), (19, '19 minutes'), (20, '20 minutes'), (21, '21 minutes'), (22, '22 minutes'), (23, '23 minutes'), (24, '24 minutes'), (25, '25 minutes'), (26, '26 minutes'), (27, '27 minutes'), (28, '28 minutes'), (29, '29 minutes'), (30, '30 minutes'), (31, '31 minutes'), (32, '32 minutes'), (33, '33 minutes'), (34, '34 minutes'), (35, '35 minutes'), (36, '36 minutes'), (37, '37 minutes'), (38, '38 minutes'), (39, '39 minutes'), (40, '40 minutes'), (41, '41 minutes'), (42, '42 minutes'), (43, '43 minutes'), (44, '44 minutes'), (45, '45 minutes'), (46, '46 minutes'), (47, '47 minutes'), (48, '48 minutes'), (49, '49 minutes'), (50, '50 minutes'), (51, '51 minutes'), (52, '52 minutes'), (53, '53 minutes'), (54, '54 minutes'), (55, '55 minutes'), (56, '56 minutes'), (57, '57 minutes'), (58, '58 minutes'), (59, '59 minutes'), (60, '60 minutes')])),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('to_do_task_date', models.DateField(blank=True, null=True)),
                ('to_do_task_message', models.TextField(blank=True, null=True, verbose_name='To Do Task Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.company')),
                ('contacts', models.ManyToManyField(related_name='calls_attended', to='crm.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Bounced', 'Bounced'), ('Opened', 'Opened'), ('Clicked', 'Clicked')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('to_do_task_date', models.DateField(blank=True, null=True)),
                ('to_do_task_message', models.TextField(blank=True, null=True, verbose_name='To Do Task Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.company')),
                ('contacts', models.ManyToManyField(related_name='emails_attended', to='crm.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
