# Generated by Django 5.1 on 2024-10-04 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0009_alter_call_users'),
        ('crm', '0019_alter_company_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='company_contacts',
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(related_name='meeting_attended', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='meeting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
