# Generated by Django 5.1 on 2024-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_agency_alter_ticket_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default='Temporary Subject', max_length=100),
        ),
    ]
