# Generated by Django 5.1 on 2024-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='complaint', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category_type',
            field=models.CharField(choices=[('client', 'Client'), ('agency', 'Agency')], default='consultant_error', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default='Temporary Subject', max_length=100),
        ),
    ]
