# Generated by Django 5.1 on 2024-10-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_category_alter_ticket_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
    ]
