# Generated by Django 5.1 on 2024-10-06 10:49

import django.db.models.deletion
from django.db import migrations, models

def create_default_subjects(apps, schema_editor):
    TicketSubject = apps.get_model('tickets', 'TicketSubject')
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Create default TicketSubjects
    default_subjects = [
        "General Inquiry",
        "Technical Support",
        "Billing Issue",
        "Feature Request",
        "Other"
    ]
    
    for subject in default_subjects:
        TicketSubject.objects.create(subject=subject)
    
    # Get the "General Inquiry" subject (or the first one if it doesn't exist)
    default_subject = TicketSubject.objects.filter(subject="General Inquiry").first() or TicketSubject.objects.first()
    
    # Update all existing tickets to use the default subject
    Ticket.objects.update(subject=default_subject)

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketsubject'),
        ),
        migrations.RunPython(create_default_subjects),
    ]