# Generated by Django 5.1 on 2024-10-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketaction',
            options={},
        ),
    ]
