# Generated by Django 4.2.16 on 2024-12-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_remove_agency_name'),
        ('tickets', '0021_auto_20241124_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsubject',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency'),
            preserve_default=False,
        ),
    ]
